### ISSUE TITLE
Deprecate "maxDuration" documentation as the prop is removed from "<Suspense>"

### ISSUE THREAD

**Issue by dance2die** [sw-yx/fresh-concurrent-react#22]
`maxDuration` has been removed on 2 Apr 2019.

References:
1. Removed from React: https://github.com/facebook/react/pull/15272
1. Removed from Flow: https://github.com/facebook/flow/pull/7613

**Comment by sw-yx** [comment]
pr?

**Comment by dance2die** [comment]
I will do a PR tomorrow 😛

**Comment by Dema** [comment]
Is it possible to revert this change and restore maxDuration until you come up with better heuristics?. Because 150ms is too small and when we use lazy loading of React components we get the flickering of the loading indicators, just what we wanted to avoid by introducing Suspense.
